{% set version = "0.9.42" %}
{% set name = "PyAutoGUI" %}

package:
  name: pyautogui
  version: {{ version }}

source:
  fn: PyAutoGUI-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9a42733505a18d6aaa4ca93445ac853cb44bf50ea4719a768d52973bfa16d2b

build:
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . -vv"  # [not linux]
    - DISPLAY=localhost:1.0 xvfb-run {{ PYTHON }} -m pip install . -vv  # [linux]

requirements:
  host:
    - python
    - pip
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]

  run:
    - python
    - pymsgbox
    - pytweening
    - pyscreeze
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]

test:
  imports:
    - pyautogui  # [not linux]
  commands:
    - DISPLAY=localhost:1.0 xvfb-run python -c "import pyautogui"  # [linux]

about:
  home: https://github.com/asweigart/pyautogui
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A cross-platform module for GUI automation for human beings. Control the keyboard and mouse from a Python script.

extra:
  recipe-maintainers:
    - jschueller
