travis:
  secure:
    BINSTAR_TOKEN: Vx7gql/JOpqSBfTj5mrQABog1Bw56aNteCAJwyoVRiZV9ZNIjVsaUmlBeedosXjIjn3MzZXCSeMoMlXcTAj367iDNoPVl0I6BBI/5TEG3uPTsLduBpYTvptD+LqrwGPqwbVixbe0qoqBcuAeoC9RXUr18d+2mrBBJxxBJd/QOTZDohq838rgc7FxJsZulaIK4LhbscsiAAllzwLhWs3JxC/9/JP/wxXtSMBagjAvnEbnnT2bW99QOwpDWarMWbEABVg8N6j/+SMl4aDOI17imO64t0UhZ6+lHssiEbH7HkPC+B99eDmJHtfp/MPlGjIWL+78gY53MR2pJ2QCLIbhRN8Cq9z3r2/gSn//RclLeK8sIM8jp/Zeew8QBDAhcu20eDATPmJMa4ErZ7AS4m9kvcsdEZ5EwxPi6y7DT+/R8TCbA3jAn1vcJGeyG97Ciqmh21WxCcKfCyMAHOo+y4BYfdictPIm+85k4jSXp39RmbEsWjK6b/AIpD/kDAjMHkn4S/c2+TFYDniuU2LqNbayC6KNVyo5v0+5BKDKDOAadbkH2MvG2f2d9SDQ2/kLQsFXeRzGREBlQNQW6MZ41jVSbzLDeiMsm4oo4TqkJf90RA8LLT6sZWz+a5AGCGSJhRV78WjkMHd+IOWUSmLQ+02QH8v08jcsHsZqxbKRVJ2dRnY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
